import Header from "@/components/custom/header";
import Refresher from "@/components/custom/refresher";
import { Toaster } from "@/components/ui/toast";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import QueryProvider from "./QueryProvider";
import StoreProvider from "./store-provider";

const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={cn("h-full", "antialiased", "font-manrope", manrope.variable)}>
      <body className="min-h-full flex flex-col">
        <StoreProvider>
          <QueryProvider>
            <Refresher>
              <Header />
              <main>{children}</main>
              <Toaster />
            </Refresher>
          </QueryProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
